# Numpy 형태변환

먼저, Shape란 무엇인가?
> shape이란 각 차원에서의 길이 조합이다
> size는 전체 원소 개수이고, **크기(모양)**는 shape이다.

**헷갈리는 부분**

보통 우리는 size를 크기라고 한다. 

근데 array에서는 size는 전체 요소 갯수이고, shape가 크기(모양)을 의미한다. 
> 일상어의 크기와 numpy가 조금 다르네~

기본적으로 reshape(), ravel(), flatten()

| 함수 | 설명 | 예시 |
|------|------|------|
| `.reshape(행, 열)` | 지정한 shape으로 변환 | `(12,) → (3, 4)` |
| `.ravel()` | 다차원 → 1차원으로 펼치기 | `(3, 4) → (12,)` |
| `.flatten()` | ravel과 유사하지만 항상 복사본 반환 | `(3, 4) → (12,)` |
| `.T` 또는 `.transpose()` | 전치 (행↔열 바꿈) | `(3, 4) → (4, 3)` |
| `.reshape(-1)` | -1은 자동 계산 | `(3, 4) → (12,)` |

참고로, reshape는 기본적으로 새 배열을 반환하므로, 변수에 재할당하지 않으면 원본은 바뀌지 않는다. 저장해서 쓰고 싶으면 다시 할당해야 한다. 
> 즉, reshape는 view를 반환한다. 그래서 변수에 받지 않으면 그 뷰가 사라지고, 원본은 그대로 남는다  
> 즉, 뷰를 만들었지만 참조하지 않으면 버려짐

In [2]:
import numpy as np

In [ ]:
arr = np.arange(1, 13) # size가 12인 벡터가 나옴. (12,)
print(arr.shape)
print(arr.size)


(12,)
12


In [6]:
re_arr = arr.reshape(4,3)
print(re_arr)
print(re_arr.shape)
print(re_arr.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
12


In [ ]:
# -1을 사용하면 자동 계산을 해준다. 12 / 4 = 3
arr_auto = arr.reshape(4, -1)
print(arr_auto)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# ravel 또는 flatten으로도 펼 수 있다. 
re_arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
# 전치로 행 열 바꾸기! 역시 shape를 바꾸는 것임

a = re_arr.reshape(3,4)
print(a)
print(a.shape)

re_arr_t = a.T
print(re_arr_t)
print(re_arr_t.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(4, 3)


# axis의 이해

axis = 0 -> 행 쪽에서 일해!
axis = 1 -> 열 쪽에서 일해!! 라는 뜻이다


```
         axis=1 →
         열0  열1  열2
   ┌──  [ 1,   2,   3]    → sum(axis=1) = 6   (행별 합)
axis=0  [ 4,   5,   6]    → sum(axis=1) = 15
   │    [ 7,   8,   9]    → sum(axis=1) = 24
   ↓
         12   15   18     ← sum(axis=0)  (열별 합)
```

만약 sum(axis =1)이라면, 좌 -> 우로 가는 것이기 떄문에 좌에서 우로 즉, 1,2,3 을 sum한다!

axis = 0이라면 행으로 일해라! 즉, 위에서 아래로 움직이겠지.. 
> 헷갈리니까 이런 식으로 생각하자~!

반드시 sum()만 되는 것은 아님. 다른 집계함수도 가능함

In [ ]:
arr = np.arange(0,120,10).reshape(3,4)
print(arr)

print(arr.sum()) # 모든 원소 다 합친다. 

print(arr.sum(axis=0)) # [120, 150, 180, 210]

print(arr.sum(axis=1)) # [60, 220, 380]

print(arr.max(axis=0)) # [80, 90, 100, 110]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
660
[120 150 180 210]
[ 60 220 380]
[ 80  90 100 110]


# 선형대수학의 사칙연산

## 벡터의 연산

뎃셈
> 덧셈이란 힘을 더하는 것이다.  
> 교환법칙이 성립한다. (행렬은 교환법칙이 성립하지 않는다)
> 각각의 좌표의 스칼라 덧셈과 같다. 
> **shape가 같아야한다**

뺄셈
> 두 힘을 곱한다
> 교환법칙이 성립하지 않는다.
> 성분끼리 빼준다. 
> **shape**가 같아야 한다. 

스칼라배
> 앞에 스칼라가 곱해진 경우

dot product
> 벡터 v1과 벡터 v2를 곱했을 때 스칼라 값이 나오도록 정의한 것이다.  
> v1 = (x1,y1) 이고 v2 = (x2,y2) 일 때, x좌표는 x좌표끼리 y좌표는 y좌표끼리 곱하는 것이다.  
> (x1x2+y1y2)이다 결과값이 스칼라가 나온다!
> **shape가 같아야 한다**(두 벡터의 요소 갯수가 완전히 동일해야한다)

dot product라는 것은 각 좌표끼리 연산을 하고 더하는 것이다. 


행렬곱셈
> 크기에 대한 제한이 정의에 있다
> ** 앞 행렬의 열과 뒷 행렬의 행의 갯수가 맞으면 가능하다. 

> A와 B의 행렬곱이란? -> A의 1행과 B의 1열을 서로 dot product한 것이다
> A mat B의 1행 2열은? A의 1행과 B의 2열을 dot prodct한 것이겠지
>
> i행 i열 원소는 A의 i행 B의 i열 원소를 dot product한 값이 원소가 된다. 
>
> 그럼 여기서!! mat mul을 하기 위해서는 어떤 조건이 나올까?
> > A의 i번쨰 행과 B의 i번쨰 열이 dot product해서 i행 i열의 원소가 되는 것이니까, dot을 하려면 행과 열의 길이가 같아야 할 것이다. 

즉, 두 행렬을 곱할 때, 크기조건: 가운데의 열과 행이 같아야 한다

그런데 우리가 헷갈리는 이유는 이것이다. 
np.dot()때문임!
> 벡터끼리 dot하면 우리가 아는 내적을 한다
> 근데 2차원 행렬 이상부터 dot을 하면, 행렬곱으로 자동 전환되어 계산한다.
> > 즉, Numpy가 아! 2차원 행렬들이니까 내가 알아서 행렬곱으로 계산할게! 이렇게 한다. 

*쉽게 생각해서 내적은 벡터와 벡터끼리 하는 것이고, 2차원 연산부터는 행렬 곱이다*

간단한 정의
- 내적: 두 벡터를 연산해서 하나의 스칼라를 만든다
- 행렬곱: 두 행렬을 연산해서 새로운 행렬을 만든다
- 연결 포인트: 행렬곱은 벡터 내적의 반복이다. 
- 행렬 곱셈 결과창의 (1, 1) 위치에 들어갈 숫자를 만들 때, 우리는 **앞 행렬의 첫 번째 '행 벡터'**와 **뒤 행렬의 첫 번째 '열 벡터'**를 꺼내서 **'내적'**을 합니다.즉, 행렬 곱이란? $\rightarrow$ "내적을 여러 번 해서 결과를 표(행렬)로 예쁘게 정리해둔 것"이라고 이해하시면 완벽합니다.

# 브로드캐스팅
Numpy broadcasting을 이해해보자

넘파이에서는 서로 shape이 달라도 일정 조건을 만족하면 연산이 가능하다. 이를 브로드캐스팅 기능이라고 한다
> 즉, shape가 다를 때, 조건이 만족한다면 shape가 부족한 부분을 확장(브로드캐스팅)하여 연산을 수행할 수 있도록 한다는 것이다. 


조건
> 1.차원의 크기가 1일때 가능하다 두 배열 간의 연산에서 최소한 하나의 배열의 차원이 1이라면(0번  축이든 1번 축이든; 1행이든 1열이든) 가능하다  
> 2.차원의 짝이 맞을 때 가능하다. 차원에 대해 축의 길이가 동일하면 브로드캐스팅이 가능하다.


간단히 말해서 
  - 같은 크기 → 그대로 연산 가능
  - 한쪽이 1 → 늘려서 연산 가능
  - 둘 다 다르고 1도 아님 → 불가능

*브로드캐스팅 이용한 일반 곱셈과 행렬곱은 완전히 다르다*

*브로드캐스팅 이용한 일반 곱셈과 행렬곱은 완전히 다르다*

1. 일반 곱셈 (*, Element-wise Product)
이 방식은 위치가 같은 요소끼리 단순히 곱하는 것입니다. 이때 브로드캐스팅이 마법을 부려 부족한 차원을 늘려줍니다.

연산 기호: * 또는 np.multiply()

특징: 두 배열의 대응하는 위치의 값들만 곱합니다.

예시: (3, 3) * (3, 1)

(3, 1) 행렬이 옆으로 복사되어 (3, 3) 모양이 됩니다.

그다음 같은 위치에 있는 방(요소)끼리 곱합니다.

결과 Shape: (3, 3) (더 큰 쪽의 모양을 따라감)

2. 행렬곱 (@, Matrix Multiplication)
우리가 수학 시간에 배운 그 방식입니다. '앞 행렬의 행'과 '뒤 행렬의 열'을 내적하여 합산합니다.

연산 기호: @ 또는 np.matmul() (또는 2차원에서 np.dot())

특징: 요소끼리 곱하기만 하는 게 아니라, 곱한 값들을 더하는 과정이 포함됩니다.

예시: (3, 3) @ (3, 1)

앞 행렬의 1행(3개)과 뒤 행렬의 1열(3개)을 곱해서 더해 하나의 숫자를 만듭니다.

결과 Shape: (3, 1) (안쪽 차원이 사라지고 바깥쪽 차원만 남음)
>  - @는 행렬곱 규칙이 먼저 적용됨
  - 그 위에 **배치 차원(앞쪽 차원)**에 대해서만 브로드캐스팅됨
  - 마지막 두 차원은 행렬곱 규칙(내적/행렬 곱의 치수 일치)을 반드시 만족해야 함

(1,4,2) 배열과 (2,2,3)은 mat mul이 가능
>  - (1, 4, 2)는 배치 차원 (1,) + 행렬 (4, 2)
  - (2, 2, 3)는 배치 차원 (2,) + 행렬 (2, 3)
  - 행렬곱 조건: 2(왼쪽 마지막 축)와 2(오른쪽 마지막에서 두 번째 축)가 일치 → OK
  - 배치 차원 (1,)과 (2,)는 브로드캐스팅 가능 → (2,)

  결과 shape: (2, 4, 3)

브로드캐스팅를 이해해보자!

형태가 다르거나 또는 배열과 스칼라 값을 연산할 수 있는 기능이다.

조건1: 두 축의 길이가 같거나

조건2: 둘 중 하나의 축이 1이면 호환한다. (즉, 1인 축에 브로드캐스팅 확장을 한다. )

In [43]:
a = np.array(
    [[1,2],[3,4]]
)

b = np.array([5,6])
# a와 b는 계산이 가능하다. 하지만, 브로드캐스팅이 없다면 a와 b의 shape가 달라서 연산이(덧셈 뺄셈) 불가능하다. 
 # • (2,)가 바로 (2,2)로 가면 어떤 축으로 복제할지 모호하기 때문이다.
#   그래서 NumPy는 규칙적으로 오른쪽 축부터 맞추며, 부족한 앞쪽 축은 1로 채워서 (1,2)로 만든다.
#   그리고 1인 축만 자동 확장되므로 (1,2) → (2,2)로 복제되는 것이다.
print(a+b)


[[ 6  8]
 [ 8 10]]


브로드캐스팅이 “맞추려고 복제”해준다는 것이다.

  b의 shape는 (2,)이고, 이것이 연산 시 암묵적으로 (1,2)로 해석된다.
  그 다음 규칙에 따라 행 방향으로 반복되어 (2,2)로 확장된다.

In [ ]:
# 예시 1: (2,3) + (3,) → b가 각 행에 자동 적용
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
# 행렬과 벡터를 더하기 위해서.. 어떻게 더하라는 이야기야? -> 넘파이가 이걸 해준다. 2,3 행렬에 맞춰서 결과를 내준다. 넘파이가 shape이 안맞을 때 사칙연산을 해준다

print(f"A shape: {A.shape}")
print(f"b shape: {b.shape}")
print(f"A - b:\n{A - b}")

# 예시 2: 스칼라와 배열의 연산 (가장 단순한 브로드캐스팅)
print(f"\nA * 2:\n{A * 2}")     # 모든 원소에 2를 곱함 # element wise하게 원소별 곱을 하는 것이다. 

# 예시 3: (3,1) + (1,3) → (3,3)
col = np.array([[1], [2], [3]])   # shape (3,1)
row = np.array([[10, 20, 30]])    # shape (1,3)

print(f"\ncol shape: {col.shape}, row shape: {row.shape}")
print(f"col + row:\n{col + row}") # (3,3) 결과

A shape: (2, 3)
b shape: (3,)
A - b:
[[ -9 -18 -27]
 [ -6 -15 -24]]

A * 2:
[[ 2  4  6]
 [ 8 10 12]]

col shape: (3, 1), row shape: (1, 3)
col + row:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 참고: 곱과 내적의 차이 이때, 내적은 벡터끼리의 곱이 아니기 때문에 dot product가 아닌 자동으로 mat mul로 처리 
print(f'곱{col*row}')
print(f'내적{col @ row}')

곱[[10 20 30]
 [20 40 60]
 [30 60 90]]
내적[[10 20 30]
 [20 40 60]
 [30 60 90]]


# 사칙연산 함수, 유니버셜 함수 

Numpy는 element wise 연산을 매우 빠르게 처리한다. 
> element wise란 배열의 각 요소끼리 1:1로 대응해 계산하는 연산이다. 예를 들어 두 배열의 같은 위치에 있는 원소들을 연산하는 것이다  
> 그럼 행렬곱은? a @ b는 element wise가 아니다. 행과 열의 곱 -합이다. 

| 함수 | 설명 | 예시 |
|------|------|------|
| `np.add(a, b)` | 덧셈 (= a + b) | `[1,2] + [3,4] = [4,6]` |
| `np.subtract(a, b)` | 뺄셈 (= a - b) | |
| `np.multiply(a, b)` | 곱셈 (= a * b) | |
| `np.divide(a, b)` | 나눗셈 (= a / b) | |
| `np.power(a, n)` | 거듭제곱 (= a ** n) | |
| `np.sqrt(a)` | 제곱근 | `sqrt(9) = 3` |
| `np.exp(a)` | 지수 (e^a) | |
| `np.log(a)` | 자연로그 (ln) | |
| `np.abs(a)` | 절대값 | |
| `np.sin(a)` | 사인 함수 | |

유니버셜 함수란? array의 모든 원소에 대해 동일한 연산을 수행하기 때문에 '유니버셜'함수이다

In [ ]:
a = [1,2,3]
b = [4,5,6]

x = np.add(a,b)
print(x)        # for 필요 없이 element wise하게 연산 가능하다!
print(type(x))
# 유니버셜 함수는 array-like(리스트 튜플)을 입력으로 받으면 내부에서 np.array로 변환해서 연산한다(자동으로 배열로 변환한다)
# 그리고 이 경우도 같은 위치 원소끼리 1:1 대응해서 연산했기 때문에 element wise 연산이다. 

[5 7 9]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

# 수학 함수 (ufunc)
print(f"\nsqrt(y)  = {np.sqrt(y)}")   # 제곱근
print(f"exp(x)   = {np.exp(x)}")      # e의 x제곱
print(f"log(y)   = {np.log(y).round(2)}")   # 자연로그
print(f"abs([-3,2,-1]) = {np.abs(np.array([-3, 2, -1]))}")  # 절대값


sqrt(y)  = [3.16227766 4.47213595 5.47722558 6.32455532]
exp(x)   = [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(y)   = [2.3  3.   3.4  3.69]
abs([-3,2,-1]) = [3 2 1]


In [57]:
np.power(2,10)

np.int64(1024)

In [61]:
x  = np.sum([1,2,3])
type(x)

numpy.int64

numpy.ndarray

## 15. 집계 함수: 통계 기초

데이터 요약에서 가장 많이 쓰는 함수들  
모두 `axis` 인자를 지정하여 행별/열별 계산 가능

| 함수 | 설명 |
|------|------|
| `np.sum()` / `.sum()` | 합계 |
| `np.mean()` / `.mean()` | 평균 |
| `np.median()` | 중앙값 |
| `np.var()` / `.var()` | 분산 |
| `np.std()` / `.std()` | 표준편차 |
| `np.min()` / `.min()` | 최솟값 |
| `np.max()` / `.max()` | 최댓값 |
| `np.argmin()` | 최솟값의 인덱스 |
| `np.argmax()` | 최댓값의 인덱스 |
| `np.cumsum()` | 누적 합계 |
| `np.cumprod()` | 누적 곱 |

In [63]:
arr = np.array([1, 2, 3, 4, 5])

# 누적 합계: 왼쪽부터 하나씩 더한 결과
print(f"원본:     {arr}")
print(f"cumsum:  {np.cumsum(arr)}")    # [1, 3, 6, 10, 15]
#   해석: 1, 1+2=3, 1+2+3=6, ...

# 누적 곱: 왼쪽부터 하나씩 곱한 결과
print(f"cumprod: {np.cumprod(arr)}")   # [1, 2, 6, 24, 120]
#   해석: 1, 1×2=2, 1×2×3=6, ...

원본:     [1 2 3 4 5]
cumsum:  [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


In [66]:
a = np.random.rand(2,4)
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.min(axis=0))
# axise 지정 가능함

[[0.23206615 0.13113451 0.45962011 0.28375434]
 [0.23284081 0.55296951 0.16394554 0.60911554]]
[0.46490696 0.68410403 0.62356565 0.89286988]
[1.10657511 1.55887141]
[0.23206615 0.13113451 0.16394554 0.28375434]


# 정렬, 고유값

| 함수 | 설명 |
|------|------|
| `np.sort(arr)` | 정렬된 **복사본** 반환 (원본 불변) |
| `arr.sort()` | 원본을 직접 정렬 (inplace) |
| `np.argsort(arr)` | 정렬 시 인덱스 순서 반환 |
| `np.unique(arr)` | 중복 제거 후 고유값 반환 |
| `np.unique(arr, return_counts=True)` | 고유값 + 빈도 |

In [67]:
arr = np.array([3, 1, 2, 3, 2, 5, 1])

# 정렬 (복사본 반환)
print(f"원본:     {arr}")
print(f"정렬:     {np.sort(arr)}")         # [1 1 2 2 3 3 5]
print(f"원본 유지: {arr}")                  # [3 1 2 3 2 5 1] — 원본 불변

# 정렬 인덱스 (어떤 순서로 정렬했는지)
print(f"\n정렬 인덱스: {np.argsort(arr)}")  # [1 6 2 4 0 3 5]

# 고유값 (중복 제거)
print(f"\n고유값:  {np.unique(arr)}")        # [1 2 3 5]

# 고유값 + 빈도
values, counts = np.unique(arr, return_counts=True)
print(f"고유값:  {values}")
print(f"빈도:    {counts}")   # [2 2 2 1] → 1이 2번, 2가 2번, 3이 2번, 5가 1번

원본:     [3 1 2 3 2 5 1]
정렬:     [1 1 2 2 3 3 5]
원본 유지: [3 1 2 3 2 5 1]

정렬 인덱스: [1 6 4 2 3 0 5]

고유값:  [1 2 3 5]
고유값:  [1 2 3 5]
빈도:    [2 2 2 1]


In [69]:
a = np.array([
    [1,2],[1,3]
])

np.unique(a,return_counts = True)

(array([1, 2, 3]), array([2, 1, 1]))

## 17. 선형대수 기초 (`np.linalg`)

행렬 곱, 역행렬, 행렬식, 고유값 등 **선형대수 연산**을 지원  
머신러닝/딥러닝에서 필수적인 기초

| 함수 | 설명 |
|------|------|
| `A @ B` 또는 `np.dot(A, B)` | 행렬 곱 |
| `A.T` | 전치행렬 |
| `np.linalg.det(A)` | 행렬식 (determinant) |
| `np.linalg.inv(A)` | 역행렬 |
| `np.linalg.eig(A)` | 고유값, 고유벡터 |
| `np.linalg.solve(A, b)` | 연립방정식 Ax=b 풀기 |
| `np.linalg.norm(v)` | 벡터 노름 (크기) |          


np.dot(A, B) -> A와 B를 내적방식으로 곱해라!  
벡터는 방향과 크기를 가진다. norm은 norm1(절댓값 더하기)과 2(피타고라스정리)가 있다. 

> `@` 연산자는 Python 3.5+에서 도입된 행렬 곱 연산자  
> `*` 연산자는 원소별 곱(element-wise)이므로 혼동 주의!

In [70]:
A = np.array([[1, 2], [3, 4]], dtype=float)
B = np.array([[5, 6], [7, 8]], dtype=float)

In [ ]:
# 행렬 곱 (@ 연산자 권장) # 행렬곱을 하면 차원 자체도 변한다.
print(A @ B)

[[19. 22.]
 [43. 50.]]


In [ ]:
# 그럼, 벡터끼리 곱하면 진짜 scalr가 나올까? 

C = np.array([1,2,3])
D = np.array([4,5,6])
print(C.shape)
print(D.shape)
print(C @ D)
# 나온다. 

(3,)
(3,)
32


In [78]:
print(A.T) # 행과 열이 바뀜

[[1. 3.]
 [2. 4.]]


In [ ]:
# ──────────────────────────────────────────────
# 고유값/고유벡터 & 연립방정식 풀기
# ──────────────────────────────────────────────
A = np.array([[1, 2], [3, 4]], dtype=float)

# 고유값 분해
eigvals, eigvecs = np.linalg.eig(A)
print(f"고유값(eigenvalues):  {eigvals}")
print(f"고유벡터(eigenvectors):\n{eigvecs}")

# 연립방정식: 2x + y = 5, x + 3y = 7  →  Ax = b
A_eq = np.array([[2, 1], [1, 3]])
b_eq = np.array([5, 7])
x = np.linalg.solve(A_eq, b_eq) # array([1.6, 1.8])
print(f"\n연립방정식 해: x={x[0]:.2f}, y={x[1]:.2f}")

# 벡터 노름 (크기/길이)
v = np.array([3, 4])
print(f"\n벡터 [3,4]의 노름: {np.linalg.norm(v)}")  # 5.0 (피타고라스)

고유값(eigenvalues):  [-0.37228132  5.37228132]
고유벡터(eigenvectors):
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

연립방정식 해: x=1.60, y=1.80

벡터 [3,4]의 노름: 5.0
