# Numpy

넘파이는 다차원 배열 객체 ndarray를 중심으로 동작한다
> 이때 ndarray는 n차원의 배열이라는 뜻이다. 

 NumPy의 ndarray는 기본적으로 같은 자료형만 저장한다. 
  다른 타입을 섞으면 모두 하나의 공통 dtype으로 자동 변환.  
  >예: int와 float를 섞으면 float로 승격됨.

파이썬 for문으로 하나씩 계산하지 말고, NumPy가 배열 전체를 한 번에 계산한다. 
  NumPy는 내부가 C로 최적화되어 있어서, 같은 작업을 훨씬 빠르게 처리함. 

  예시:

파이썬 for 루프  
  a = [1, 2, 3, 4]
  b = []
  for x in a:
      b.append(x * 2)

NumPy 벡터화  
  import numpy as np
  a = np.array([1, 2, 3, 4])
  b = a * 2

  두 코드의 결과는 같지만, NumPy 방식이 훨씬 빠르고 간단하다!

# ndarray 만들기

넘파이의 핵심 자료구조인 ndarray를 만들어보자. 
파이썬 리스트를 `np.array()`에 넣으면 NumPy 배열로 변환

> NumPy의 핵심인 ndarray가 **선형대수의 기본 객체(스칼라, 벡터, 행렬, 텐서)**를 그대로 표현한다.
  즉, 수학적 개념과 코드 구조가 1:1로 대응되므로 선형대수 개념을 알아야 배열 연산이 왜 그렇게 동작하는지 이해가 된다.

*그럼 스칼라는 0d arrary인가?*
-> yes!!

In [1]:
import numpy as np

In [4]:
# 배열 생성하기 
# NumPy에서는 스칼라, 벡터, 행렬, 텐서를 모두 **ndarray의 차원수(0d, 1d, 2d, 3d…)**로 구분해 다룬다.

# nd array
array0d = np.array(1)  # od array(스칼라)


array1d = np.array([1,2,3,4,5]) # 1d array(벡터)

array2d = np.array(
    [[1,2,3],
    [4,5,6]]
) # 2d array(행렬)

print(array0d)
print(array1d)
print(array2d)


1
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## 3d array(텐서)

shape(3,4,3)인 경우를 생각해보자

**이 경우 행이 4, 열이 3인 행렬이 3개 있는 경우이다.**
> 즉, (차원, 행, 열)로 보면 쉽다. 

* 텐서에서 3차원을 쌓인 구조로 이해하면 쉽다!!

In [ ]:
array3d = np.array(
    [[[1,2,3],
    [4,5,6],
    [7,8,9]]]
)

print(array3d.shape)
# (1,3,3)이 나온다. 즉, (3,3) 행렬이 1개 있는 것이다.
# 그렇다는 것은 맨 앞의 차원은 겉에 []가 쌓인 갯수이겠다!

(1, 3, 3)


In [ ]:
# shape가 (2,3,2)을 만들어보자

arr3d = np.array([
    [[1,2],
    [3,4],
    [5,6]],   
    [[7,8],
    [9,10],
    [11,12]]
])

print(arr3d.shape)
print(arr3d)

#   - arr3d는 **3차원 ndarray**이다.
#   - shape는 (2, 3, 2)이다.
#       - 첫 번째 축: 2개 블록이다.
#       - 두 번째 축: 각 블록마다 3행이다.
#       - 세 번째 축: 각 행마다 2열이다.
#   - 따라서 2개의 3x2 행렬이 쌓인 구조이다.

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
# (3,3,1) 즉, 행이 3개, 열이 1개인 행렬이 3개 쌓여 있는 텐서를 만들아어보자

arr3d_1 = np.array([
    [[1],
    [2],
    [3]],
    [[4],
    [5],
    [6]],
    [[7],
    [8],
    [9]]
])

arr3d_1.shape

(3, 3, 1)

  - 대괄호 하나 = 1차원 요소 묶음이다.
    예: [1, 2, 3] → 1d
  - **대괄호 두 겹 = “행(row)들의 묶음”**이다.
    예: [[1,2,3], [4,5,6]] → 2d (2행, 3열)
  - **대괄호 세 겹 = “행렬들의 묶음”**이다.
    예: [[[1,2],[3,4]], [[5,6],[7,8]]] → 3d (2개 블록, 각 2행 2열)

  핵심 공식이다.

  - 차원 수 = 중첩된 대괄호 층 수
  - shape = 바깥부터 안쪽으로 개수 읽기

## array의 핵심 속성 보기

| 속성 | 반환값 | 설명 |
|------|--------|------|
| `.ndim` | 정수 | 차원 수 (1차원=1, 2차원=2, ...) |
| `.shape` | 튜플 | 각 차원의 길이 (예: (2, 3) = 2행 3열) |
| `.size` | 정수 | 전체 원소 수 (shape의 곱) |
| `.dtype` | 타입 | 데이터 타입 (int64, float64 등) |
| `.itemsize` | 정수 | 원소 1개의 바이트 크기 |
| `.nbytes` | 정수 | 전체 메모리 사용량 (= size × itemsize) |

In [16]:
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
arr3d.ndim

3

In [18]:
arr3d.shape

(2, 3, 2)

In [20]:
arr3d.size
# 12가 나올 것이다. 왜? size는 전체 원소 갯수의 합이니까
# (2,3,2)이기 때문에 2*3*2 = 12

12

In [21]:
arr3d.dtype

dtype('int64')

In [ ]:
print(arr3d.itemsize)
# arr3d.itemsize은 배열 안의 원소 1개당 메모리에서 몇 바이트를 차지하는지 보여주는 함수이다. 
# 알 수 있는 것은 Numpy의 ndarray는 모든 요소가 같은 dtype이므로 각 요소의 바이트 크기가 동일할 것이다. 그러므로 전체 메모리 사용량은 itemsize*size일 것이다

print(arr3d.nbytes)

8
96


## array 생성 함수
### array를 만들어보자

물론, 리스트를 np.array()로 감싸서 만들 수 있겠지만, 매번 그렇게 할 수 없잖아? 또, 차원이 많아지면 복잡함. 

| 함수 | 설명 | 예시 결과 |
|------|------|----------|
| `np.zeros(shape)` | 0으로 채운 배열 | `[0. 0. 0.]` |
| `np.ones(shape)` | 1로 채운 배열 | `[1. 1. 1.]` |
| `np.full(shape, val)` | 특정 값으로 채운 배열 | `[7 7 7]` |
| `np.eye(n)` | n×n 단위행렬 | 대각선 1, 나머지 0 |
| `np.arange(start, stop, step)` | 등간격 정수 (끝값 미포함) | `[0 2 4 6 8]` |
| `np.linspace(start, stop, num)` | 균등 분할 (끝값 포함) | `[0. 0.25 0.5 0.75 1.]` |
| `np.empty(shape)` | 초기화 없는 빈 배열 (빠르지만 쓰레기값) | 랜덤 값 |

In [25]:
zero = np.zeros((2,2,2))
print(zero)
print(zero.shape)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)


In [ ]:
one = np.ones((3))
print(one)
print(one.shape)

one1 = np.ones((3,1))
print(one1)
print(one1.shape)
#  (3,)는 **1차원 배열(길이 3)**이다.
#   (3,1)은 **2차원 배열(3행 1열)**이다.
#   1차원 배열은 축이 하나뿐이라서 “행”도 “열”도 없고, 그냥 길이 3만 존재한다.그래서 (3,)으로 표기되는 것이다.


#   - (3,) = 축이 1개, 길이 3인 1차원 배열이다.
#   - (,3) 같은 표기는 파이썬 튜플 문법에 존재하지 않는다.
#   - 가로/세로 방향은 1차원에는 없다. 방향은 2차원부터 의미가 생긴다


[1. 1. 1.]
(3,)
[[1.]
 [1.]
 [1.]]
(3, 1)


(3,) VS (3,1)

>(3,) 벡터: 3개의 요소가 한 줄로 쭉 이어진 1차원 구조입니다. 단순한 데이터의 나열로 볼 수 있습니다.

> (3,1) 행렬: **3개의 행(Row)**과 **1개의 열(Column)**로 이루어진 2차원 구조입니다. 세로로 긴 표 형태를 띠고 있습니다.

In [28]:
five = np.full((2,3,2),5)
print(five)

[[[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]]


In [47]:
a = np.eye(3) # 3,3 단위행렬을 만든다

In [ ]:
b = np.random.rand(3,3)
print(b)
print('\n')
print(a@b) # 단위행렬 a와 3,3 행렬 b를 곱하니 그대로 나옴
# 즉, 단위행렬이란 곱셈의 항등원이다. 어떤 연산을 해도 값이 변하지 않게 하는 특별한 원소인 항등원임. 행렬곱의 항등원은 단위 행렬이다. 

[[0.73447477 0.97296167 0.41344245]
 [0.34651143 0.36553029 0.54335244]
 [0.18625284 0.31846468 0.08594485]]


[[0.73447477 0.97296167 0.41344245]
 [0.34651143 0.36553029 0.54335244]
 [0.18625284 0.31846468 0.08594485]]


In [32]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
print(range(1,10))
# range 함수 사용범
# 파이썬의 range함수는 특정 구간의 숫자의 범위를 만들어주는 함수이다. 이 함수를 이용하면 특정 횟수 만큼 반복하는 반복문을 만들기 유용하다.

range(1, 10)


In [ ]:
print(type(range(1,10))) # range객체이다
# range 객체는 정수의 연속을 반복 가능한 객체이다. 리스트처럼 모든 값을 메모리에 저장하지 않고, 시작과 끝 간격 정보만 저장한다. 그래서 반복 가능하지만, 리스트 자료형과는 다르다

print(type(np.arange(1,100,5))) # ndarray 자료형이다

<class 'range'>
<class 'numpy.ndarray'>


range() 함수에 대해

range함수 매개변수에 숫자를 한개만 넣는 경우
range(A) 
0부터 A-1 까지의 정수 범위를 반환합니다. A까지가 아닌 A-1 이다


range함수 매개변수에 숫자를 두개 넣는 경우 
range(A, B)
A부터 B-1 까지의 정수 범위를 반환합니다. B까지가 아닌 B-1 이다

range()는 반복문 for과 많이 사용한다



np.arange()와 비교
  - range()는 파이썬 내장 함수이고 리스트가 아닌 range 객체를 만든다이다.
  - np.arange()는 NumPy 함수이고 ndarray를 만든다이다.

  차이 핵심이다.

  - 자료형
      - range() → range 객체(반복용)이다.
      - np.arange() → NumPy 배열이다.
  
r = range(5)      # 0,1,2,3,4 반복용  
a = np.arange(5)  # array([0,1,2,3,4]) -> 즉, 1차원 array를 만든다. 보통 만든 뒤에 reshape를 해서 2차원 이상으로 바꾼다. 

In [38]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.empty((2,3,2))

array([[[4.67296746e-307, 1.69121096e-306],
        [9.45698831e-308, 1.89146896e-307],
        [7.56571288e-307, 3.11525958e-307]],

       [[1.24610723e-306, 1.29061142e-306],
        [9.79113983e-307, 1.22382967e-307],
        [1.37962388e-306, 1.78019625e-306]]])

# 데이터 타입

astype()으로 '자료형'을 다른 타입으로 바꿀 수 있다.

>• astype의 as는 “~로(as)” 변환한다는 의미이다.
  즉, astype는 자료형을 다른 타입으로 바꾼다는 뜻이다.

In [ ]:
# 배열 생성 시 dtype 지정
a = np.array([1, 2, 3], dtype=np.int32)
print(f"a = {a}, dtype = {a.dtype}, itemsize = {a.itemsize}bytes")

# astype()으로 타입 변환 → 새로운 배열을 반환 (원본 불변)
b = a.astype(np.float64)
print(f"b = {b}, dtype = {b.dtype}, itemsize = {b.itemsize}bytes")

# 실수 → 정수 변환 시 소수점 이하 버림
c = np.array([1.9, 2.7, 3.1])
d = c.astype(np.int32)
print(f"\n실수: {c} → 정수: {d}")   # [1 2 3] — 반올림이 아니라 버림!

# dtype 혼합 시 자동 변환 (upcasting)
mixed = np.array([1, 2.5, 3])   # int + float → float64로 통일
print(f"\n혼합 입력: {mixed}, dtype = {mixed.dtype}")
# array의 요소는 dtype이 모두 같아야 하니까!! (리스트랑 다르다)

# 인덱싱과 슬라이싱

NumPy 배열의 기본 인덱싱은 리스트와 같다.
  하지만 다차원 인덱싱과 고급 인덱싱이 추가로 있다.

2차원 부터는 arr[행,열] 방식으로 인덱싱을 진행한다

```
          열0   열1   열2   열3
행0  →  [ 10,   20,   30,   40 ]
행1  →  [ 50,   60,   70,   80 ]
행2  →  [ 90,  100,  110,  120 ]

arr[0, 1] = 20     (0번 행, 1번 열)
arr[2, 3] = 120    (2번 행, 3번 열)
```

슬라이싱

- 시작: 포함 / 끝: **미포함** / 간격: 생략 시 1
- 2차원: `arr[행 슬라이스, 열 슬라이스]`

2차원에서는 행과 열을 동시에 슬라이싱한다
arr[0:2, 1:3] 처럼!

3차원에서는?  
  arr[0]          # 첫 번째 블록 (3x4)  
  arr[:, 1, :]    # 모든 블록에서 1번 행만  
  arr[1, :, 2:]   # 1번 블록, 모든 행, 열 2부터 끝까지  
  arr[:, :, ::2]  # 모든 블록, 모든 행, 열을 2칸 간격으로  


In [ ]:
arr = np.array([
    [10,  20,  30,  40],    # 행0
    [50,  60,  70,  80],    # 행1
    [90, 100, 110, 120]     # 행2
])

In [ ]:
# 단일 원소 접근: arr[행, 열]
print(f"\narr[0, 1] = {arr[0, 1]}")     # 20 (0행 1열)  
print(f"arr[2, 3] = {arr[2, 3]}")       # 120 (2행 3열)  [2,3] 처럼 쉼표로 구분되어 있네..? -> array가 2차원 행렬인 경우이기 때문에 이렇게 표기한다.

# 행 전체 / 열 전체 선택
print(f"\narr[1]   = {arr[1]}")          # [50 60 70 80] — 1행 전체
print(f"arr[:, 2] = {arr[:, 2]}")        # [30 70 110] — 모든 행의 2열

# 부분 배열 슬라이싱: arr[행 범위, 열 범위]
print(f"\narr[1:, 2:]:\n{arr[1:, 2:]}")  # 1행부터, 2열부터
#     → [[70, 80],
#        [110, 120]]


print(f"\narr[:, ::2]:\n{arr[:, ::2]}")   # 모든행, 0·2열만
# • ::는 슬라이싱 문법 start:stop:step에서 start와 stop을 생략하고 step만 쓰는 형태이기 때문이다.
#   즉 ::2는 처음부터 끝까지 2칸씩이라는 뜻이다.

#   그래서 arr[:, ::2]는

#   - : → 모든 행
#   - ::2 → 열을 2칸 간격으로 선택
#     이라는 의미이다.

## 불리언 인덱싱 (Boolean Indexing)

조건식을 이용해 **원하는 원소만 추출**하는 방법  
데이터 필터링에서 매우 자주 사용 — pandas의 필터링도 이 원리

```
원리:
scores = [55, 78, 92, 45, 88]    ← 원본 배열
scores >= 70                      ← 조건식
→ [False, True, True, False, True]  ← 불리언 마스크
scores[mask]                      ← True인 위치만 추출
→ [78, 92, 88]
```

In [ ]:
# ──────────────────────────────────────────────
# 불리언 인덱싱으로 조건부 추출
# ──────────────────────────────────────────────
scores = np.array([55, 78, 92, 45, 88, 61])

# 1) 조건식 → 불리언 마스크(True/False 배열) 생성
mask = scores >= 70
print(f"원본:        {scores}")
print(f"mask(>=70):  {mask}")      # [False  True  True False  True False]

# 2) 마스크로 원소 추출
print(f"70점 이상:   {scores[mask]}")       # [78 92 88]

# 3) 한 줄로 쓰기 (가장 많이 쓰는 형태)
print(scores[(scores >= 50) & (scores <= 80)])  # AND 조건
print(scores[(scores < 50) | (scores >= 90)]) # OR 조건

# 주의: and/or 대신 & / | 사용, 각 조건을 괄호()로 감싸야 함

원본:        [55 78 92 45 88 61]
mask(>=70):  [False  True  True False  True False]
70점 이상:   [78 92 88]
[55 78 61]
50미만|90이상: [92 45]


In [80]:
(scores >= 50) & (scores <= 80)

array([ True,  True, False, False, False,  True])

## 팬시 인덱싱 (Fancy Indexing)

**정수 배열을 인덱스로 사용**하여 원하는 위치를 비순차적으로 선택

```
arr = [100, 200, 300, 400, 500]
idx = [4, 2, 0]     ← 선택할 위치
arr[idx] → [500, 300, 100]   ← 원하는 순서로 추출
```


> 즉, 인덱싱용 배열을 만들어서 인덱싱한다 -> 팬시 인덱싱

In [99]:
# ──────────────────────────────────────────────
# 팬시 인덱싱: 인덱스 배열로 선택
# ──────────────────────────────────────────────
arr = np.array([100, 200, 300, 400, 500])
idx = np.array([4, 2, 0])   # 선택할 인덱스

print(f"원본:     {arr}")
print(f"인덱스:   {idx}")
print(f"선택결과: {arr[idx]}")   # [500 300 100]

# 2차원에서의 팬시 인덱싱
arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

idx2 = [0,2]
# 0행과 2행만 선택
print(f"\n0행, 2행 선택:\n{arr2d[idx2]}")

# 또는
print(f"\n0행, 2행 선택:\n{arr2d[[0,2]]}")

# 열 선택
print(f"\n2열 선택:\n{arr2d[:,2]}")

# 행과 열 선택
arr2d[[1],[1]]

원본:     [100 200 300 400 500]
인덱스:   [4 2 0]
선택결과: [500 300 100]

0행, 2행 선택:
[[10 20 30]
 [70 80 90]]

0행, 2행 선택:
[[10 20 30]
 [70 80 90]]

2열 선택:
[30 60 90]


array([50])

# 주의할점

NumPy 슬라이싱은 기본적으로 **뷰(view)**를 반환 → 원본과 메모리를 공유  
뷰를 수정하면 **원본도 함께 변경됨** — 주의 필요!

> 여기서 뷰를 반환한다란?  
> 원본 배열과 같은 메모리를 공유하는 창(배열)을 돌려준다는 의미이
  다.
  즉, 새로 복사된 배열이 아니라 같은 데이터에 대한 다른 모양/범위를 보여주는 배열이다.

  그래서 뷰를 수정하면 같은 메모리를 쓰는 원본도 함께 바뀌는 것이다.

In [104]:
array_x = np.zeros((5,3))
print(array_x)
print(array_x[[0],[0]])

array_x[[0],[0]] = 3

print(array_x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.]
[[3. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
